import matplotlib.pyplot as plt
import numpy as np

before_loss = np.loadtxt("../before_loss.txt")
before_accuracy = np.loadtxt("../before_accuracy.txt")

after_loss = np.loadtxt("../after_loss.txt")
after_accuracy = np.loadtxt("../after_accuracy.txt")

after_loss_128 = np.loadtxt("../after_loss_128.txt")
after_accuracy_128 = np.loadtxt("../after_accuracy_128.txt")

after_loss_256 = np.loadtxt("../after_loss_256.txt")
after_accuracy_256 = np.loadtxt("../after_accuracy_256.txt")

after_loss_3layers = np.loadtxt("../after_loss_3layers.txt")
after_accuracy_3layers = np.loadtxt("../after_accuracy_3layers.txt")

plt.subplot(1, 2, 1)
plt.plot(np.array(range(35)), before_loss, label="base model, single, 100")
plt.plot(np.array(range(35)), after_loss, label="improve model, (64, 32)")
plt.plot(np.array(range(35)), after_loss_128, label="improve model, (128, 64)")
plt.plot(np.array(range(35)), after_loss_256, label="improve model, (256, 128)")
plt.title("Loss vs Epochs")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend(loc="best")
plt.subplot(1, 2, 2)
plt.plot(np.array(range(35)), before_accuracy, label="base model, single, 100")
plt.plot(np.array(range(35)), after_accuracy, label="improve model, (64, 32)")
plt.plot(np.array(range(35)), after_accuracy_128, label="improve model, (128, 64)")
plt.plot(np.array(range(35)), after_accuracy_256, label="improve model, (256, 128)")
plt.title("Accuracy vs Epochs")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend(loc="best")
plt.show()

# plt.subplot(1, 2, 1)
# plt.plot(np.array(range(35)), before_loss, label="base model, 1x2 layers")
# plt.plot(np.array(range(35)), after_loss_128, label="improve model, 2x2 layers")
# plt.plot(np.array(range(35)), after_loss_3layers, label="improve model, 3x2 layers")
# plt.title("Loss vs Epochs")
# plt.xlabel("Epochs")
# plt.ylabel("Loss")
# plt.legend(loc="best")
# plt.subplot(1, 2, 2)
# plt.plot(np.array(range(35)), before_accuracy, label="base model, 1x2 layers")
# plt.plot(np.array(range(35)), after_accuracy_128, label="improve model, 2x2 layers")
# plt.plot(np.array(range(35)), after_accuracy_3layers, label="improve model, 3x2 layers")
# plt.title("Accuracy vs Epochs")
# plt.xlabel("Epochs")
# plt.ylabel("Accuracy")
# plt.legend(loc="best")
# plt.show()